from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
from typing import List, Tuple
from qiskit import QuantumCircuit
from qiskit.primitives import StatevectorSampler
import os

# Import your engines
from qpu_bridge import get_quantum_randomness
from quantum_optimizer import solve_logistics_problem

app = FastAPI()

# --- INPUT MODEL ---
class LogisticsRequest(BaseModel):
    routes: List[Tuple[int, int]]

# --- API ROUTES (The Brains) ---

@app.get("/generate-quantum-number")
def quantum_endpoint():
    print(">>> Spooling up Randomness Engine...")
    data = get_quantum_randomness()
    return {
        "source": "Real Quantum Computer (IBM Cloud)",
        "raw_data": data,
        "status": "success"
    }

@app.post("/optimize-logistics")
def optimize_endpoint(request: LogisticsRequest):
    print(f">>> Optimization Request received for {len(request.routes)} routes.")
    result = solve_logistics_problem(request.routes)
    return {
        "algorithm": "QAOA (Quantum Approximate Optimization Algorithm)",
        "optimization_result": result
    }

# --- FRONTEND ROUTE (The Face) ---
# This serves your index.html when someone visits the main URL
@app.get("/")
def read_root():
    return FileResponse('index.html')

@app.get("/api/quantum-random")
def generate_quantum_random_number():
    try:
        # 1. Create a Quantum Circuit with 1 Qubit
        qc = QuantumCircuit(1)
        
        # 2. Apply Hadamard Gate (H-Gate)
        # This puts the qubit into a 50/50 Superposition of 0 and 1
        qc.h(0)
        
        # 3. Measure the qubit
        qc.measure_all()
        
        # 4. Run the simulation
        sampler = StatevectorSampler()
        job = sampler.run([qc], shots=1)
        result = job.result()[0].data.meas.get_counts()
        
        # 5. Extract the bit (it will be '0' or '1')
        random_bit = list(result.keys())[0]
        
        return {
            "status": "success",
            "type": "Quantum Simulation (Superposition)",
            "value": int(random_bit),
            "explanation": "Generated by collapsing a qubit from superposition state |+>."
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}

# If you had more static files (images/css), you'd mount them here.
# For now, we just need index.html.